---
Azure: 
    CosmosDB:
     #   ConnectionString: mongodb://poc-stn-mongo:q5JsqDUTXUdqBM7J1vM9zZgDXgoUKzQdQxsXkaO6Y0QffbPrMiQaRIdIE4bo6QQ3pOICCIdUqp8AEbyrD651sw==@poc-stn-mongo.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
     ConnectionString: mongodb://stn-euw-cosmos-be-nprd:ovspjzhTC2peTCbZrpHwpAdHWPjOWAdTGERgmPFWhUw8nMuFv87QGXrK2eD4jCXCTw0A3oYsNToQxQrK8PKhWA==@stn-euw-cosmos-be-nprd.documents.azure.com:10255/?ssl=true&replicaSet=globaldb