---
Logging: 
    LogLevel:
        Default: Debug
        System: Information
        Microsoft: Information
API: 
    Name: SafeToNet SafetyIndicator API
    Environment: Development    

Database: 
    Name: safetyIndicator
    Collection:      
     - safetyIndicators

AppVersion: 
    VersionNumber: 1.0.0